#!/usr/bin/env bash
set -Eeuo pipefail

# Project-WARP-Unlock SmartDNS version
# Features:
# - Download latest wgcf automatically
# - amd64 / arm64 auto-detect
# - SmartDNS instead of dnsmasq
# - Selectable stack mode:
#     1) dual  -> IPv4 + IPv6 policy routing
#     2) ipv4  -> IPv4 only policy routing
#     3) ipv6  -> IPv6 only policy routing
#     4) none  -> only generate WireGuard config, no PostUp/PreDown hooks
# - Uses numeric routing table 250 for Debian 12 / Debian 13 compatibility
# - In IPv6-enabled modes, adds high-metric IPv6 default route for: curl -6 --interface wg ...

WG_IF="${WG_IF:-wg}"
WG_DIR="/etc/wireguard"
WG_CONF="${WG_DIR}/${WG_IF}.conf"
WGCF_BIN="${WG_DIR}/wgcf"
WGCF_ACCOUNT="${WG_DIR}/wgcf-account.toml"
WGCF_VERSION="${WGCF_VERSION:-latest}"

ROUTE_TABLE_ID="${ROUTE_TABLE_ID:-250}"
MARK="${MARK:-2}"

# dual / ipv4 / ipv6 / none
STACK_MODE="${STACK_MODE:-__ASK__}"

# By default, keep the Endpoint generated by wgcf.
# You can override it when running:
# WARP_ENDPOINT=162.159.193.1:2408 ./run.sh
WARP_ENDPOINT="${WARP_ENDPOINT:-}"

SMARTDNS_CONF="/etc/smartdns/smartdns.conf"

log() {
  echo -e "\033[1;32m[Info]\033[0m $*"
}

warn() {
  echo -e "\033[1;33m[Warn]\033[0m $*"
}

err() {
  echo -e "\033[1;31m[Error]\033[0m $*" >&2
}

require_root() {
  if [ "${EUID}" -ne 0 ]; then
    err "Please run as root."
    exit 1
  fi
}

select_stack_mode() {
  # If STACK_MODE was explicitly provided by environment, accept it after validation.
  # Otherwise show an interactive menu.
  if [ -n "${STACK_MODE:-}" ] && [ "${STACK_MODE}" != "__ASK__" ]; then
    case "${STACK_MODE}" in
      dual|ipv4|ipv6|none)
        log "Selected stack mode from environment: ${STACK_MODE}"
        return 0
        ;;
      *)
        warn "Invalid STACK_MODE from environment: ${STACK_MODE}"
        ;;
    esac
  fi

  echo
  echo "请选择 WARP 分流模式："
  echo "  1) 双栈 IPv4 + IPv6 分流，推荐"
  echo "  2) 只启用 IPv4 分流"
  echo "  3) 只启用 IPv6 分流"
  echo "  4) 不添加分流 hook，只生成普通 WireGuard 配置"
  echo

  local choice
  while true; do
    read -r -p "请输入选项 [1-4]，默认 1: " choice
    choice="${choice:-1}"

    case "${choice}" in
      1)
        STACK_MODE="dual"
        break
        ;;
      2)
        STACK_MODE="ipv4"
        break
        ;;
      3)
        STACK_MODE="ipv6"
        break
        ;;
      4)
        STACK_MODE="none"
        break
        ;;
      *)
        echo "无效选项，请输入 1、2、3 或 4。"
        ;;
    esac
  done

  log "Selected stack mode: ${STACK_MODE}"
}

want_ipv4() {
  [ "${STACK_MODE}" = "dual" ] || [ "${STACK_MODE}" = "ipv4" ]
}

want_ipv6() {
  [ "${STACK_MODE}" = "dual" ] || [ "${STACK_MODE}" = "ipv6" ]
}

want_hooks() {
  [ "${STACK_MODE}" != "none" ]
}

detect_arch() {
  local arch
  arch="$(uname -m)"

  case "${arch}" in
    x86_64|amd64)
      WGCF_ARCH="amd64"
      SMARTDNS_ARCHES=("x86_64" "amd64")
      ;;
    aarch64|arm64)
      WGCF_ARCH="arm64"
      SMARTDNS_ARCHES=("aarch64" "arm64")
      ;;
    *)
      err "Unsupported architecture: ${arch}. Only amd64 and arm64 are supported."
      exit 1
      ;;
  esac

  log "Detected architecture: ${arch}, wgcf arch: ${WGCF_ARCH}"
}

apt_install_base() {
  log "Installing base dependencies..."

  export DEBIAN_FRONTEND=noninteractive

  apt-get update
  apt-get install -y \
    ca-certificates \
    curl \
    wget \
    tar \
    gzip \
    wireguard \
    wireguard-tools \
    dnsutils \
    mtr \
    lsof \
    procps \
    sed \
    gawk \
    grep

  if want_hooks; then
    apt-get install -y ipset iptables
  fi

  mkdir -p "${WG_DIR}"
}

install_smartdns() {
  if command -v smartdns >/dev/null 2>&1; then
    log "SmartDNS already installed: $(smartdns -v 2>&1 | head -n 1 || true)"
    return 0
  fi

  log "Trying to install SmartDNS from apt..."

  if apt-get install -y smartdns >/dev/null 2>&1; then
    log "SmartDNS installed from apt."
    return 0
  fi

  warn "apt install smartdns failed. Trying SmartDNS GitHub release package..."

  local api url tmp file arch_pattern
  api="https://api.github.com/repos/pymumu/smartdns/releases/latest"
  tmp="$(mktemp -d)"
  url=""

  for arch_pattern in "${SMARTDNS_ARCHES[@]}"; do
    url="$(curl -fsSL "${api}" \
      | grep -E '"browser_download_url":' \
      | sed -E 's/.*"browser_download_url": *"([^"]+)".*/\1/' \
      | grep -Ei "${arch_pattern}.*(linux-all\.tar\.gz|debian-all\.deb)$" \
      | head -n 1 || true)"

    if [ -n "${url}" ]; then
      break
    fi
  done

  if [ -z "${url}" ]; then
    err "Cannot find SmartDNS package for this architecture."
    err "Please install SmartDNS manually, then rerun this script."
    exit 1
  fi

  log "Downloading SmartDNS package: ${url}"

  file="${tmp}/smartdns.pkg"
  curl -fL "${url}" -o "${file}"

  if echo "${url}" | grep -q '\.deb$'; then
    dpkg -i "${file}" || apt-get -f install -y
  elif echo "${url}" | grep -q '\.tar\.gz$'; then
    tar -zxf "${file}" -C "${tmp}"
    local install_script
    install_script="$(find "${tmp}" -type f -name install | head -n 1 || true)"

    if [ -z "${install_script}" ]; then
      err "SmartDNS install script not found in package."
      exit 1
    fi

    chmod +x "${install_script}"
    cd "$(dirname "${install_script}")"
    ./install -i
  else
    err "Unknown SmartDNS package format: ${url}"
    exit 1
  fi

  rm -rf "${tmp}"

  if ! command -v smartdns >/dev/null 2>&1; then
    err "SmartDNS installation failed."
    exit 1
  fi

  log "SmartDNS installed: $(smartdns -v 2>&1 | head -n 1 || true)"
}

disable_dnsmasq_and_resolved() {
  log "Disabling dnsmasq and systemd-resolved if present..."

  systemctl disable --now dnsmasq >/dev/null 2>&1 || true
  systemctl stop dnsmasq >/dev/null 2>&1 || true

  systemctl disable --now systemd-resolved >/dev/null 2>&1 || true
  systemctl stop systemd-resolved >/dev/null 2>&1 || true

  if [ -L /etc/resolv.conf ]; then
    rm -f /etc/resolv.conf
  else
    cp -a /etc/resolv.conf "/etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
  fi

  cat > /etc/resolv.conf <<'EOF'
nameserver 127.0.0.1
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF
}

install_wgcf() {
  log "Installing wgcf..."

  local version url

  if [ "${WGCF_VERSION}" = "latest" ]; then
    version="$(curl -fsSL https://api.github.com/repos/ViRb3/wgcf/releases/latest \
      | grep -E '"tag_name":' \
      | sed -E 's/.*"tag_name": *"v?([^"]+)".*/\1/' \
      | head -n 1)"
  else
    version="${WGCF_VERSION#v}"
  fi

  if [ -z "${version}" ]; then
    err "Failed to detect wgcf latest version."
    exit 1
  fi

  url="https://github.com/ViRb3/wgcf/releases/download/v${version}/wgcf_${version}_linux_${WGCF_ARCH}"

  log "Downloading wgcf v${version} for linux_${WGCF_ARCH}: ${url}"

  curl -fL "${url}" -o "${WGCF_BIN}"
  chmod +x "${WGCF_BIN}"

  log "wgcf installed: $("${WGCF_BIN}" --version 2>/dev/null || echo "v${version}")"
}

filter_wireguard_addresses() {
  local input="$1"
  local output="$2"

  case "${STACK_MODE}" in
    dual)
      cp "${input}" "${output}"
      ;;
    ipv4)
      # Keep only IPv4 Address lines.
      awk '
        /^Address *=/ {
          if ($0 ~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/) print
          next
        }
        { print }
      ' "${input}" > "${output}"
      ;;
    ipv6)
      # Keep only IPv6 Address lines.
      awk '
        /^Address *=/ {
          if ($0 ~ /:/) print
          next
        }
        { print }
      ' "${input}" > "${output}"
      ;;
    none)
      # Keep original dual-stack wgcf profile in plain mode.
      cp "${input}" "${output}"
      ;;
  esac
}

generate_warp_profile() {
  log "Generating WARP WireGuard profile..."

  mkdir -p "${WG_DIR}"
  cd "${WG_DIR}"

  if [ ! -f "${WGCF_ACCOUNT}" ]; then
    "${WGCF_BIN}" register --accept-tos --config "${WGCF_ACCOUNT}"
  else
    log "Existing wgcf account found: ${WGCF_ACCOUNT}"
  fi

  "${WGCF_BIN}" generate --config "${WGCF_ACCOUNT}" --profile "${WG_CONF}.raw"

  log "Normalizing WireGuard profile..."

  local filtered_profile
  filtered_profile="${WG_CONF}.filtered"
  filter_wireguard_addresses "${WG_CONF}.raw" "${filtered_profile}"

  if want_hooks; then
    awk '
      /^\[Interface\]/ {
        print
        print "Table = off"
        print "PostUp = /etc/wireguard/up"
        print "PreDown = /etc/wireguard/down"
        next
      }

      /^Table *=/ { next }
      /^PostUp *=/ { next }
      /^PreDown *=/ { next }
      /^PostDown *=/ { next }
      /^PreUp *=/ { next }
      /^DNS *=/ { next }
      /^PersistentKeepalive *=/ { next }

      {
        print
      }

      END {
        print "PersistentKeepalive = 5"
      }
    ' "${filtered_profile}" > "${WG_CONF}"
  else
    awk '
      /^Table *=/ { next }
      /^PostUp *=/ { next }
      /^PreDown *=/ { next }
      /^PostDown *=/ { next }
      /^PreUp *=/ { next }
      /^DNS *=/ { next }
      /^PersistentKeepalive *=/ { next }

      {
        print
      }

      END {
        print "PersistentKeepalive = 5"
      }
    ' "${filtered_profile}" > "${WG_CONF}"
  fi

  if [ -n "${WARP_ENDPOINT}" ]; then
    log "Overriding WireGuard Endpoint: ${WARP_ENDPOINT}"
    sed -i -E "s#^Endpoint *=.*#Endpoint = ${WARP_ENDPOINT}#g" "${WG_CONF}"
  else
    log "Keeping default wgcf Endpoint."
  fi

  chmod 600 "${WG_CONF}"

  log "WireGuard profile written to ${WG_CONF}"
}

write_smartdns_conf() {
  log "Writing SmartDNS config: ${SMARTDNS_CONF}"

  mkdir -p /etc/smartdns /var/log

  if [ -f "${SMARTDNS_CONF}" ]; then
    cp -a "${SMARTDNS_CONF}" "${SMARTDNS_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
  fi

  cat > "${SMARTDNS_CONF}" <<'EOF'
log-level warn
log-file /var/log/smartdns.log
log-size 128k
log-num 1
response-mode fastest-response
cache-size 512
rr-ttl 60
bind [127.0.0.1]:53

server 1.1.1.1 -bootstrap-dns -fallback
server 8.8.8.8 -bootstrap-dns -fallback
server-quic 8.8.8.8:853
server-h3 h3://cloudflare-dns.com/dns-query
server-https https://nrt.core.access.zznet.fun/dns-query -group 1stream -exclude-default-group

EOF

  if want_ipv4 && want_ipv6; then
    cat >> "${SMARTDNS_CONF}" <<'EOF'
# Netflix
ipset /netflix.ca/#4:warp
ipset /netflix.ca/#6:warp6
ipset /netflix.com/#4:warp
ipset /netflix.com/#6:warp6
ipset /netflix.net/#4:warp
ipset /netflix.net/#6:warp6
ipset /netflixinvestor.com/#4:warp
ipset /netflixinvestor.com/#6:warp6
ipset /netflixtechblog.com/#4:warp
ipset /netflixtechblog.com/#6:warp6
ipset /nflxext.com/#4:warp
ipset /nflxext.com/#6:warp6
ipset /nflximg.com/#4:warp
ipset /nflximg.com/#6:warp6
ipset /nflximg.net/#4:warp
ipset /nflximg.net/#6:warp6
ipset /nflxsearch.net/#4:warp
ipset /nflxsearch.net/#6:warp6
ipset /nflxso.net/#4:warp
ipset /nflxso.net/#6:warp6
ipset /nflxvideo.net/#4:warp
ipset /nflxvideo.net/#6:warp6

# Google / YouTube
ipset /google.com/#4:warp
ipset /google.com/#6:warp6
ipset /play.googleapis.com/#4:warp
ipset /play.googleapis.com/#6:warp6
ipset /android.googleapis.com/#4:warp
ipset /android.googleapis.com/#6:warp6
ipset /googlevideo.com/#4:warp
ipset /googlevideo.com/#6:warp6
ipset /youtube.com/#4:warp
ipset /youtube.com/#6:warp6
ipset /youtubei.googleapis.com/#4:warp
ipset /youtubei.googleapis.com/#6:warp6
ipset /fonts.googleapis.com/#4:warp
ipset /fonts.googleapis.com/#6:warp6
ipset /yt3.ggpht.com/#4:warp
ipset /yt3.ggpht.com/#6:warp6

# Test domains
ipset /ipinfo.io/#4:warp
ipset /ipinfo.io/#6:warp6
ipset /ip.sb/#4:warp
ipset /ip.sb/#6:warp6
ipset /cloudflare.com/#4:warp
ipset /cloudflare.com/#6:warp6

EOF
  elif want_ipv4; then
    cat >> "${SMARTDNS_CONF}" <<'EOF'
# Netflix
ipset /netflix.ca/warp
ipset /netflix.com/warp
ipset /netflix.net/warp
ipset /netflixinvestor.com/warp
ipset /netflixtechblog.com/warp
ipset /nflxext.com/warp
ipset /nflximg.com/warp
ipset /nflximg.net/warp
ipset /nflxsearch.net/warp
ipset /nflxso.net/warp
ipset /nflxvideo.net/warp

# Google / YouTube
ipset /google.com/warp
ipset /play.googleapis.com/warp
ipset /android.googleapis.com/warp
ipset /googlevideo.com/warp
ipset /youtube.com/warp
ipset /youtubei.googleapis.com/warp
ipset /fonts.googleapis.com/warp
ipset /yt3.ggpht.com/warp

# Test domains
ipset /ipinfo.io/warp
ipset /ip.sb/warp
ipset /cloudflare.com/warp

EOF
  elif want_ipv6; then
    cat >> "${SMARTDNS_CONF}" <<'EOF'
# Netflix
ipset /netflix.ca/#6:warp6
ipset /netflix.com/#6:warp6
ipset /netflix.net/#6:warp6
ipset /netflixinvestor.com/#6:warp6
ipset /netflixtechblog.com/#6:warp6
ipset /nflxext.com/#6:warp6
ipset /nflximg.com/#6:warp6
ipset /nflximg.net/#6:warp6
ipset /nflxsearch.net/#6:warp6
ipset /nflxso.net/#6:warp6
ipset /nflxvideo.net/#6:warp6

# Google / YouTube
ipset /google.com/#6:warp6
ipset /play.googleapis.com/#6:warp6
ipset /android.googleapis.com/#6:warp6
ipset /googlevideo.com/#6:warp6
ipset /youtube.com/#6:warp6
ipset /youtubei.googleapis.com/#6:warp6
ipset /fonts.googleapis.com/#6:warp6
ipset /yt3.ggpht.com/#6:warp6

# Test domains
ipset /ipinfo.io/#6:warp6
ipset /ip.sb/#6:warp6
ipset /cloudflare.com/#6:warp6

EOF
  else
    cat >> "${SMARTDNS_CONF}" <<'EOF'
# STACK_MODE=none: no ipset routing rules are written.

EOF
  fi

  touch /var/log/smartdns.log
  chmod 644 /var/log/smartdns.log
}

write_wireguard_hooks() {
  if ! want_hooks; then
    log "STACK_MODE=none: skipping WireGuard hook scripts."
    rm -f /etc/wireguard/up /etc/wireguard/down
    return 0
  fi

  log "Writing WireGuard hook scripts..."

  cat > /etc/wireguard/up <<EOF
#!/usr/bin/env bash
set -e

WG_IF="${WG_IF}"
TABLE_ID="${ROUTE_TABLE_ID}"
MARK="${MARK}"
STACK_MODE="${STACK_MODE}"

want_ipv4() {
  [ "\${STACK_MODE}" = "dual" ] || [ "\${STACK_MODE}" = "ipv4" ]
}

want_ipv6() {
  [ "\${STACK_MODE}" = "dual" ] || [ "\${STACK_MODE}" = "ipv6" ]
}

if want_ipv4; then
  ipset create warp hash:ip family inet -exist

  iptables -t mangle -N fwmark 2>/dev/null || true
  iptables -t mangle -C PREROUTING -j fwmark 2>/dev/null || iptables -t mangle -A PREROUTING -j fwmark
  iptables -t mangle -C OUTPUT -j fwmark 2>/dev/null || iptables -t mangle -A OUTPUT -j fwmark
  iptables -t mangle -C fwmark -m set --match-set warp dst -j MARK --set-mark "\$MARK" 2>/dev/null || \\
  iptables -t mangle -A fwmark -m set --match-set warp dst -j MARK --set-mark "\$MARK"

  ip rule add fwmark "\$MARK" table "\$TABLE_ID" 2>/dev/null || true
  ip route replace default dev "\$WG_IF" table "\$TABLE_ID"

  iptables -t nat -C POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE 2>/dev/null || \\
  iptables -t nat -A POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE

  iptables -t mangle -C POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \\
  iptables -t mangle -A POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
fi

if want_ipv6; then
  ipset create warp6 hash:ip family inet6 -exist

  ip6tables -t mangle -N fwmark6 2>/dev/null || true
  ip6tables -t mangle -C PREROUTING -j fwmark6 2>/dev/null || ip6tables -t mangle -A PREROUTING -j fwmark6
  ip6tables -t mangle -C OUTPUT -j fwmark6 2>/dev/null || ip6tables -t mangle -A OUTPUT -j fwmark6
  ip6tables -t mangle -C fwmark6 -m set --match-set warp6 dst -j MARK --set-mark "\$MARK" 2>/dev/null || \\
  ip6tables -t mangle -A fwmark6 -m set --match-set warp6 dst -j MARK --set-mark "\$MARK"

  ip -6 rule add fwmark "\$MARK" table "\$TABLE_ID" 2>/dev/null || true
  ip -6 route replace default dev "\$WG_IF" table "\$TABLE_ID"

  # High-metric IPv6 default route for manual tests:
  # curl -6 --interface wg https://ip.sb
  # Native IPv6 default route should still win if it has lower metric.
  ip -6 route replace default dev "\$WG_IF" metric 4096

  ip6tables -t nat -C POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE 2>/dev/null || \\
  ip6tables -t nat -A POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE

  ip6tables -t mangle -C POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \\
  ip6tables -t mangle -A POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
fi
EOF

  cat > /etc/wireguard/down <<EOF
#!/usr/bin/env bash

WG_IF="${WG_IF}"
TABLE_ID="${ROUTE_TABLE_ID}"
MARK="${MARK}"
STACK_MODE="${STACK_MODE}"

want_ipv4() {
  [ "\${STACK_MODE}" = "dual" ] || [ "\${STACK_MODE}" = "ipv4" ]
}

want_ipv6() {
  [ "\${STACK_MODE}" = "dual" ] || [ "\${STACK_MODE}" = "ipv6" ]
}

if want_ipv4; then
  iptables -t mangle -D PREROUTING -j fwmark 2>/dev/null || true
  iptables -t mangle -D OUTPUT -j fwmark 2>/dev/null || true
  iptables -t mangle -D fwmark -m set --match-set warp dst -j MARK --set-mark "\$MARK" 2>/dev/null || true
  iptables -t mangle -D POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || true
  iptables -t mangle -F fwmark 2>/dev/null || true
  iptables -t mangle -X fwmark 2>/dev/null || true

  iptables -t nat -D POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE 2>/dev/null || true

  ip rule del fwmark "\$MARK" table "\$TABLE_ID" 2>/dev/null || true
  ip route flush table "\$TABLE_ID" 2>/dev/null || true

  ipset destroy warp 2>/dev/null || true
fi

if want_ipv6; then
  ip6tables -t mangle -D PREROUTING -j fwmark6 2>/dev/null || true
  ip6tables -t mangle -D OUTPUT -j fwmark6 2>/dev/null || true
  ip6tables -t mangle -D fwmark6 -m set --match-set warp6 dst -j MARK --set-mark "\$MARK" 2>/dev/null || true
  ip6tables -t mangle -D POSTROUTING -o "\$WG_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || true
  ip6tables -t mangle -F fwmark6 2>/dev/null || true
  ip6tables -t mangle -X fwmark6 2>/dev/null || true

  ip6tables -t nat -D POSTROUTING -m mark --mark "\$MARK" -j MASQUERADE 2>/dev/null || true

  ip -6 rule del fwmark "\$MARK" table "\$TABLE_ID" 2>/dev/null || true
  ip -6 route flush table "\$TABLE_ID" 2>/dev/null || true
  ip -6 route del default dev "\$WG_IF" metric 4096 2>/dev/null || true

  ipset destroy warp6 2>/dev/null || true
fi
EOF

  chmod +x /etc/wireguard/up /etc/wireguard/down
}

configure_sysctl() {
  if ! want_hooks; then
    log "STACK_MODE=none: skipping sysctl forwarding config."
    return 0
  fi

  log "Configuring sysctl forwarding..."

  {
    if want_ipv4; then
      echo "net.ipv4.ip_forward=1"
    fi

    if want_ipv6; then
      echo "net.ipv6.conf.all.forwarding=1"
      echo "net.ipv6.conf.default.forwarding=1"
    fi
  } > /etc/sysctl.d/99-warp-unlock.conf

  sysctl --system >/dev/null || true
}

enable_services() {
  log "Enabling services..."

  systemctl daemon-reload

  systemctl enable smartdns >/dev/null 2>&1 || true
  systemctl restart smartdns

  systemctl enable "wg-quick@${WG_IF}" >/dev/null 2>&1 || true
  systemctl restart "wg-quick@${WG_IF}"
}

run_checks() {
  log "Running checks..."

  echo
  echo "===== Mode ====="
  echo "STACK_MODE=${STACK_MODE}"

  echo
  echo "===== WireGuard config addresses ====="
  grep -E "^(Address|Table|PostUp|PreDown|Endpoint|AllowedIPs)" "${WG_CONF}" || true

  echo
  echo "===== WireGuard ====="
  wg show || true

  if want_ipv4; then
    echo
    echo "===== IPv4 policy routing ====="
    ip rule | grep "lookup ${ROUTE_TABLE_ID}" || true
    ip route show table "${ROUTE_TABLE_ID}" || true
  fi

  if want_ipv6; then
    echo
    echo "===== IPv6 policy routing ====="
    ip -6 rule | grep "lookup ${ROUTE_TABLE_ID}" || true
    ip -6 route show table "${ROUTE_TABLE_ID}" || true
    ip -6 route | grep "${WG_IF}" || true
  fi

  echo
  echo "===== SmartDNS test ====="
  dig @127.0.0.1 youtube.com A +short || true
  dig @127.0.0.1 youtube.com AAAA +short || true

  if want_ipv4; then
    echo
    echo "===== ipset warp ====="
    ipset list warp 2>/dev/null | sed -n '1,20p' || true
    echo
    echo "===== IPv4 mangle counters ====="
    iptables -t mangle -vnL fwmark 2>/dev/null || true
    echo
    echo "===== IPv4 curl test ====="
    curl -4 --connect-timeout 8 https://ipinfo.io --interface "${WG_IF}" || true
    echo
  fi

  if want_ipv6; then
    echo
    echo "===== ipset warp6 ====="
    ipset list warp6 2>/dev/null | sed -n '1,20p' || true
    echo
    echo "===== IPv6 mangle counters ====="
    ip6tables -t mangle -vnL fwmark6 2>/dev/null || true
    echo
    echo "===== IPv6 curl test ====="
    curl -6 --connect-timeout 8 https://ip.sb --interface "${WG_IF}" || true
    echo
  fi
}

main() {
  require_root
  select_stack_mode
  detect_arch
  apt_install_base
  install_smartdns
  disable_dnsmasq_and_resolved
  install_wgcf
  generate_warp_profile
  configure_sysctl
  write_smartdns_conf
  write_wireguard_hooks
  enable_services
  run_checks

  echo
  log "Done."
  log "Stack mode: ${STACK_MODE}"
  log "SmartDNS config: ${SMARTDNS_CONF}"
  log "WireGuard config: ${WG_CONF}"
  log "Hook scripts: /etc/wireguard/up /etc/wireguard/down"
  log "Routing table id: ${ROUTE_TABLE_ID}"
}

main "$@"
